### ISSUE TITLE
Trouble with ctypes import into python

### ISSUE THREAD

**Issue by skier4291** [berndporr/rplidar_rpi#1]
Hello,
Thank you for uploading this project, it has been very helpful in getting my slamtec rplidar working with my raspberry pi.  I've been attempting to compile the a1lidarrpi.cpp as a shared object output file and import it into python as I wish to manipulate the incoming data in python, however I'm running into issues with the linking. 

The compile command I'm currently using is:
sudo g++ -fPIC -shared -o a1lidarrpi.so a1lidarrpi.cpp -lstdc++ -lpigpio

Which generates the a1lidarrpi.so and then I am attempting to load the library using the following two lines in python:

import ctypes
lidar = ctypes.CDLL("/home/admin/rplidar_rpi/a1lidarrpi.so")

When ran I receive the following error:
OSError: /home/admin/rplidar_rpi/a1lidarrpi.so: undefined symbol: _ZN2rp10standalone7rplidar13RPlidarDriver12CreateDriverEj

I ran into two previous undefined symbol errors which were solved by the addition of -lstdc++ -lpigpio on the compile command, however I am at a loss on how to approach this undefined symbol linking error.  It appears to me to be looking for the driver for the RPLidar, is that referencing the driver in the rplidar_sdk? If so, how would I go about linking that?

Any help resolving this undefined symbol error would be much appreciated.  Also if you know of a better way to implement python bindings to use your C++ program in python, I am open to that option as well.

Thanks for your time.

**Comment by berndporr** [comment]
Sorry but I have no idea how ctypes works. I also don't know if it can handle callbacks properly. I have only been working with swig and there you could directly put the source files into the setup.py and write an .i file. Again, I'm not sure if swig can handle the callback as it is with the const reference array. It might work. It certainly would work with a const std::vector or const std::array as I've done that before: https://github.com/berndporr/pyusbdux. Feel free to send a pull request once you have figured it out but I cannot do debugging with you, sorry.
